KnpLabs/DoctrineBehaviors

src/Model/Sluggable/SluggableMethods.php
tests/Knp/DoctrineBehaviors/ORM/SluggableMultiTest.php
tests/fixtures/BehaviorFixtures/ORM/SluggableMultiEntity.php

Use getters when getting field values for Sluggable, if property does not exist (solves problem with accessing non-existent field, like in translations)

Try to use getters when getting non-existent field values for Sluggable

---

README.md
composer.json
src/Model/Sluggable/SluggableMethods.php
src/Model/Sluggable/Transliterator.php
tests/Knp/DoctrineBehaviors/ORM/SluggableMultiTest.php
tests/Knp/DoctrineBehaviors/ORM/SluggableTest.php
tests/fixtures/BehaviorFixtures/ORM/SluggableMultiEntity.php

Replace iconv usage with behat/transliterator, add some test cases.
Slug generation from cyrillic string now works.

Slug generation from cyrillic strings

---

README.md
src/Model/Translatable/TranslationMethods.php
src/ORM/Translatable/TranslatableSubscriber.php
tests/Knp/DoctrineBehaviors/ORM/TranslatableTest.php
tests/fixtures/BehaviorFixtures/ORM/TranslatableCustomizedEntity.php
tests/fixtures/BehaviorFixtures/ORM/Translation/TranslatableCustomizedEntityTranslation.php

- As discussed, I enforced the use of the trait methods in the translatable listener
- I created the inverse method to retrieve the in the translation entity
- I created 2 more fixture entities (I'm not 100% happy with their naming but I couldn't come up with a better one). I put the translation into a nested namespace to "break" the default rule of the "Translation" suffix.
- I added a test for verifying the oneToMany relationship also for the "customized" case. Since the 2 tests were equal, I factored its logic into a private assertion method in the test case class which now takes as parameters the 2 classes to verify the association for.
- I updated the relevant section in the readme
Hope this is ok, let me know if I need to change anything :)

Issue #172: ability to choose the class translation name

---

README.md
src/Model/Tree/Node.php
src/Model/Tree/NodeInterface.php

with this patch it is possible to another key than the `ID` for generating the materialized path. (i wanted to use the slug field instead)
you can override `getTreeNodeField` for that purpose:
```php
public function getNodeId()
{
if (!$this->getSlug()) {
$this->generateSlug();
}
return $this->getSlug();
}
```

added customizable tree identifier

---

.travis.yml

If this does not pass, then the version constraints should be stricter.

run tests with the lowest possible versions

---

README.md

Use `PropertyAccessor` instead of `proxyCurrentLocaleTranslation` to get translations.
In `PHP` scripts we simply could get translated heading by:
```php
$entity->getHeading();
```
But also it will be very useful for `Twig` templates:
``` jinja
<h1>{{ entity.heading }}</h1>
{# will be called "getHeading()", "heading()", "isHeading()", "hasHeading()" or "__get()" in this case #}
```

Use PropertyAccessor for get translations

---

src/ORM/Loggable/LoggerCallable.php

the symfony logger is depreacted, use the psr logger is better here, since it allows usage outside of symfony aswell

use psr logger instead of symfony logger

---

src/Model/Translatable/TranslatableMethods.php
src/ORM/Translatable/TranslatableSubscriber.php

This allows to have ManyToOne association as location
```
/**
* @var \Acme\Locale $locale
*
* @ORM\ManyToOne(targetEntity="Locale")
* @ORM\JoinColumn(name="locale", referencedColumnName="id", nullable=false)
*/
protected $locale;
```

Allow locale as an association entity

---

src/ORM/Blameable/BlameableSubscriber.php

Blameable does not consider the isRecursive setting but used hardcoded values. So the trait is not found when used in a parent class.

Make Blameable respect the isRecursive setting

---

src/ORM/Translatable/TranslatableSubscriber.php

Locale setting does not work for newly created objects. But this can be fixed by adding subscription to `prePersist` lifecycle callback.

Set current and default locale on prePersist event

---

README.md

Hello,
The documentation doesn't currently give a way to override default naming strategy globally for translatable behaviors.
I wrote this part of doc and re-organize some part.
ksom

Add documentation to override the default naming strategy for translatable

---

README.md
src/Bundle/DependencyInjection/Configuration.php
src/Bundle/DependencyInjection/DoctrineBehaviorsExtension.php
src/Bundle/DoctrineBehaviorsBundle.php

You can now enable/disable behaviors you don't want using the bundle config.
By default, all behaviors are enabled. As soon as `knp_doctrine_behaviors` is
specified, all behaviors are disabled and the developer need to specify which
ones he want to enable.
This fix conflict issues, for example when a `setCurrentLocale` method is
defined by another third-party library/bundle.
This way does not introduce BC breaks, but only a new feature. The best would
be to add some interfaces and use them in subscribers. But that would imply
a major release... Maybe for the next one :-)

Make Behaviors configurable.

---

src/ORM/Translatable/CurrentLocaleCallable.php

In Symfony 3.0, scopes and the 'request' service have been removed.
This commit fixes that while preserving BC.

Fixes compatibility for Symfony 3.0

---

src/ORM/Translatable/TranslatableSubscriber.php

When starting from the owning side (translation entity) it could be nice to save the reversed side (translatable entity) automatically. So I enabled cascade merge and persist when mapping a translation in the TranslatableSubscriber.php.

Translatable: enable cascade persist and merge on the owning side 

---

README.md
config/orm-services.yml
src/ORM/Timestampable/TimestampableSubscriber.php
tests/Knp/DoctrineBehaviors/ORM/TimestampableTest.php

We came across this issue when working with a Postgres database. The `datetime` field in pg ignores the timezone which was causing us some headaches. This PR allows you to define the field type as a parameter rather than (as we have done in our current project) overriding the whole subscriber class - which, incidentally, has a number of private methods and properties which make for an unnecessarily large override file. Have added some docs too.

Timestampable - add db field type parameter

---

src/Model/Translatable/TranslatableMethods.php
tests/Knp/DoctrineBehaviors/ORM/TranslatableTest.php

When working with **language_COUNTRY** locales, it is common to fallback to language only translations. However, Translatable could only fallback to the default locale. This PR fixes this.
Maybe it has to be enhanced, as it uses the same **$fallbackToDefault** parameter as the one that already exists, but its usage isn't quite the same. If you previously relied on the fallback of **fr_FR** to **en** instead of **fr**, you will have a BC break (currently no unit tests show this).
See the code of the [Symfony translation component](https://github.com/symfony/translation/blob/master/Translator.php#L392) for reference.

Language only fallback

---

.travis.yml

Doctrine dev-master is incompatible with PHP 5.4, which causes Travis to error. This PR excludes that configuration, so it will not error anymore.

Fixes Travis checks

---

src/Model/Translatable/TranslatableMethods.php

Use late static bindings (replace `self::` by `static::`) for `TranslatableMethods::doTranslate()`.
Use case:
```php
abstract class Foo
{
use Translatable;
}
class Baz
{
use Translation;
public static function getTranslatableEntityClass()
{
return Bar::class;
}
}
class Bar extends Foo
{
public static function getTranslationEntityClass()
{
return Baz::class;
}
}

TranslatableMethods: use late static bindings

---

src/Model/Loggable/Loggable.php
src/Model/SoftDeletable/SoftDeletableMethods.php
src/Model/Timestampable/TimestampableMethods.php
tests/Knp/DoctrineBehaviors/ORM/LoggableTest.php

Hi there,
So I was writing some tests and found out that the Timestampable, SoftDeletable and Loggable behaviours where ignoring microseconds which was causing some issue in my enviroment.
This PR adds microseconds to the Timestampable, SoftDeletable and Loggable behaviours. 
Let me know what you think.
Cheers,
Warnar
P.S. the `$dateTime->setTimezone` is needed because for some reason the unix timestamp changes based on the timezone in PHP.

Microseconds

---

config/orm-services.yml

Not quoting a scalar starting with the "%" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0.
https://github.com/symfony/symfony/blob/3.1/UPGRADE-3.1.md#yaml

Fixes for Symfony 3.1

---

config/orm-services.yml
src/ORM/Translatable/TranslatableSubscriber.php
tests/Knp/DoctrineBehaviors/ORM/TranslatableTest.php

When using a JoinedInheritance for translations, the `TranslatableSubscriber` will try to map the children classes, which will create a new unique index on a column existing only in the parent class' table (`translatable_id`).
This crashes Doctrine.
Anyway, the fields need, associations and indexes only to be mapped for the root class of the translation hierarchy, since they will all be inherited. This is true for every kind of inheritance and every behaviour.
This PR fixes the issue for Translatable.

Fix interaction between translations & joined inheritance

---

.travis.yml

In `--testdox` mode we can't see what exactly causes errors

Run PHPUnit in normal mode instead of --testdox

---

src/Bundle/DependencyInjection/DoctrineBehaviorsExtension.php

In `orm-services.yml` the service defined as `knp.doctrine_behaviors.softdeletable_subscriber` but `DoctrineBehaviorsExtension` tries to remove `knp.doctrine_behaviors.soft_deletable_subscriber`

Fix disabling softdeletable

---

src/ORM/Translatable/TranslatableSubscriber.php

There are cases where you could have a entity with the setCurrentLocale method, but that is not a translatable entity managed by KNP.
This PR only sets the default and current locales on entities that are translatable instead of relying on a method existance.
Closes https://github.com/KnpLabs/DoctrineBehaviors/issues/314
Closes https://github.com/KnpLabs/DoctrineBehaviors/pull/315
It also fixes compatibility with Sylius, because it uses its own translations implementation, and it is incompatible with having this other bundle installed.

Only set locales on entities managed by knp translations

---

README.md

IMHO we need to prepare a `v2` for upcoming changes breaking BC (for instance #241).
I didn't create `v1` branch so far, I'd like some feedback first. I think we need to either:
* Create a `v2` branch, keep v1 on `master` for now and put v2 on `master` later, when it got released ;
* Or create `v1` right now and put `v2` on master, but we have to change the base branch of every current PR.
@nicolasmure @Soullivaneuh WDYT?

Document master and v1 branches

---

src/Bundle/DependencyInjection/Configuration.php

A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0
#408 There is one opened issue about it.

Fix config deprecation

---

UPGRADE.md
src/ORM/Translatable/TranslatableSubscriber.php

Currently, the mapping for locale columns does not provide any length,
thus Doctrine falls back to the default size: 255 chars.
Not only such size is useless, but it also prevents using this library
with utf8mb4 charset, because InnoDB indexes are capped at 767 bytes,
and unfortunately: 4 * 255 = 1020 bytes.
For reference, here is the error with utf8mb4 charset:
> SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key
> was too long; max key length is 767 bytes
Fixes #384 and #388.

Shrink locale columns to 5 chars

---

README.md
composer.json
docs/sortable.md
ecs.yaml
src/ORM/Blameable/BlameableSubscriber.php
src/ORM/Geocodable/GeocodableSubscriber.php
tests/AbstractBehaviorTestCase.php
tests/ORM/BlameableTest.php
tests/ORM/SoftDeletableTest.php

Remove scheduleExtraUpdate calls

---

ecs.yaml
src/Model/Sluggable/SluggableMethodsTrait.php
tests/Fixtures/Entity/SluggableWithoutRegenerateEntity.php
tests/ORM/SluggableWithoutRegenerateTest.php

This PR aims to fix the bug described in the issue #471 
If the getRegenerateSlugOnUpdate  method return false, the slug will be generate if its value is null. 
This behavior seems legit because you can set the slug manually and it won't be regenerated. However if you set manually the slug value to null, it will be regenerated (the setter doesn't allow this anyway).

Fix slug generation if the getRegenerateSlugOnUpdate method return false

---

src/EventSubscriber/BlameableSubscriber.php

Fixes https://github.com/KnpLabs/DoctrineBehaviors/issues/492
For me this fixes a loop which made PHP crash. I am not sure why this happened but moving the unitOfWork access to the functions would make sense anyway.

Moved unitOfWork access to methods instead of constructor

---

config/services.yaml
docs/blameable.md
src/EventSubscriber/BlameableSubscriber.php
src/Provider/UserProvider.php
tests/Fixtures/Entity/BlameableEntityWithUserEntity.php
tests/ORM/BlameableWithEntityTest.php
tests/Provider/EntityUserProvider.php
tests/config/config_test_with_blameable_entity.yaml

Closes #486 
I can't find a way to get the user in the security provider. In order to make Blameable works well, a added the parameter `doctrine_behaviors_blameable_user_entity` which allows the user to define the entity to use

[Blameable] Added new parameter to allow definition of the user entity

---

composer.json
config/services.yaml
src/Provider/LocaleProvider.php
tests/config/config_test.yaml

In the versions <2 the `%locale%` parameter was used as the fallback locale. Now we are trying to get the `defaultLocale` from the Request which is fine IMO. But we should use the `%locale%` parameter if no reqest exists.
I am aware that the `%locale%` parameter is now mandatory again. Is this a problem? Should we switch to `%kernel.default_locale%` which would require that we require `symfony/framework` as a dependency AFAIK.
Fixing this issue is mostly important because now there is no default locale set on cli.

Add another layer for locale fallback - %locale% parameter

---

composer.json
tests/ORM/BlameableTest.php
tests/ORM/BlameableWithEntityTest.php
tests/ORM/SluggableMultiTest.php
tests/ORM/SluggableTest.php
tests/ORM/SluggableWithoutRegenerateTest.php
tests/ORM/SoftDeletableTest.php
tests/ORM/TimestampableTest.php
tests/ORM/TranslatableInheritanceTest.php
tests/ORM/TranslatableTest.php

A backwards-compatibility layer has been added to persistence to help
consumers move to the new namespacing. It is based on class aliases,
which means the type declaration changes should not be a BC-break: types
are the same.
See doctrine/persistence#71
This means:
- using the new namespaces
- adding autoload calls for new types to types that may be extended and
use persistence types in type declarations of non-constructor methods,
so that signature compatibility is recognized by old versions of php.
Luckily, none of those were found in this package.
More details on this at
https://dev.to/greg0ire/how-to-deprecate-a-type-in-php-48cf

Address deprecations from persistence lib

---

.gitignore
src/EventSubscriber/BlameableSubscriber.php
src/EventSubscriber/SoftDeletableSubscriber.php
src/EventSubscriber/TimestampableSubscriber.php
src/EventSubscriber/TranslatableSubscriber.php
src/EventSubscriber/TreeSubscriber.php
src/EventSubscriber/UuidableSubscriber.php
tests/ORM/TimestampableMakeEntityTest.php
tests/config/config_test_with_timestampable_entity.yaml

Resolves issue #481 by checking for a null reflection class pointer before
using the pointer, in each of the event subscribers.

Make:entity dispatches event with incomplete argument

---

docs/sluggable.md

The method seems to have been renamed from `getRegenerateSlugOnUpdate()` to `shouldRegenerateSlugOnUpdate()`.

Fix method name in documentation

---

composer.json

This will allow auto-registering bundles with Symfony Flex. See https://github.com/KnpLabs/DoctrineBehaviors/issues/497#issuecomment-586757750 for details

add type "symfony-bundle" for packagist

---

README.md
extension.neon
phpstan.neon
src/Model/Translatable/TranslatableMethodsTrait.php
src/PHPStan/Type/Helper.php
src/PHPStan/Type/TranslatableGetTranslationsDynamicMethodReturnTypeExtension.php
src/PHPStan/Type/TranslatableTranslateDynamicMethodReturnTypeExtension.php
src/PHPStan/Type/TranslationGetTranslatableDynamicMethodReturnTypeExtension.php
tests/Fixtures/Entity/TranslatableEntity.php
tests/ORM/TranslatableInheritanceTest.php

This PR is a proposal for #516, and aim to replace #435. 
**Before:** at b8a4b015645af6f53beeabe1f34cb3ba17405206 with 69 errors:
```
➜  DoctrineBehaviors git:(d) vendor/bin/phpstan analyze
Note: Using configuration file /home/kocal/Dev/DoctrineBehaviors/phpstan.neon.
95/95 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
------ ----------------------------------------------------------------------------------------------------- 
Line   tests/ORM/SluggableWithTranslatableEntityAndUniquenessTest.php                                       
------ ----------------------------------------------------------------------------------------------------- 
29     Call to an undefined method Knp\DoctrineBehaviors\Contract\Entity\TranslationInterface::setTitle().  
30     Call to an undefined method …
```

Add PHPStan extensions, for Translatable/Translation interfaces

---

src/Provider/LocaleProvider.php

Hello,
This pull request aims to use the `kernel.default_locale` parameter if no parameter named `locale` is set.

Default locale provider handling

---

ecs.php
phpstan.neon
rector-ci.php
tests/ORM/TranslatableTest.php
utils/phpstan-behaviors/src/Type/TranslationTypeHelper.php

Fix #588 
@TomasVotruba There are some PHPStan issues `Do not use "$entityManager->getRepository()" outside of the constructor of repository service` but are not related to this PR. They were already present in master.
I've also configured ECS and Rector to run over `utils` directory. What do you think?

fix(phpstan): allow PHPStan to run over Translatable/Translation interfaces, close #588

---

.travis.yml
composer.json

Fix #590. 
I've added more Travis jobs to test both doctrine/common 2 and 3 versions.
I had to allow doctrine/persistence ^2.0 too, since doctrine/common ^3.0 requires it.

feat: add doctrine/common 3 support, close #590

---

README.md

_"voilà"_ is the correct way to write this word in french.

Changed "Voilá!" to "voilà!"

---

composer.json

symplify/package-builder does not appear to be used other than for testing purposes

Move package-builder to dev dependency

---

src/Repository/DefaultSluggableRepository.php
tests/Repository/DefaultSluggableRepositoryTest.php

Also fixes tables with composite primary keys, and removes the assumption that `Sluggable::getId()` exists.

Handle embeddable as primary key in sluggables

---

src/Model/Translatable/TranslatablePropertiesTrait.php

`Collection<TranslationInterface>` should be preferred over `TranslationInterface[]|Collection`

Improve phpdoc of TranslatablePropertiesTrait

---

src/Contract/Entity/TranslatableInterface.php
src/Model/Translatable/TranslatableMethodsTrait.php
src/Model/Translatable/TranslatablePropertiesTrait.php

When using [Collection](https://github.com/doctrine/collections/blob/42a111afab917a328fdc38a35101c089ce52b580/lib/Doctrine/Common/Collections/Collection.php#L27-L32), it need to specify the type of the key.
In case of `Translatable` the key is the locale:
https://github.com/KnpLabs/DoctrineBehaviors/blob/a6a4bf3b118137de11b9913a76c58ae89f68c307/src/Model/Translatable/TranslatableMethodsTrait.php#L55-L57

Fix Collection template usages

---

phpstan.neon
src/EventSubscriber/TranslatableEventSubscriber.php
tests/Fixtures/Entity/TranslatableCustomIdentifierEntity.php
tests/Fixtures/Entity/TranslatableCustomIdentifierEntityTranslation.php
tests/ORM/Translatable/TranslatableTest.php

In case you want to use something else then 'id'.
Is it also possible to make a 2.2.1 release for php 7 support if this is approved?

use ClassMetadataInfo to determine the referencedColumnName

---

docs/translatable.md
tests/ORM/TreeNodeTest.php

I created a piece of documentation for these lazy loading options. 
So it is very clear that no join on any table is getting performed.

Update documentation for #285.

---

phpstan.neon
src/EventSubscriber/TranslatableEventSubscriber.php
tests/Fixtures/Entity/Translatable/ExtendedTranslatableEntityWithJoinTableInheritance.php
tests/Fixtures/Entity/Translatable/ExtendedTranslatableEntityWithJoinTableInheritanceTranslation.php
tests/Fixtures/Entity/Translatable/TranslatableEntityWithJoinTableInheritance.php
tests/Fixtures/Entity/Translatable/TranslatableEntityWithJoinTableInheritanceTranslation.php
tests/ORM/Translatable/TranslatableJoinTableInheritanceTest.php

This PR adds a failing test and a fix for #307 #317 and #336.
**As a short summary:** 
Whenever you use doctrine joined inheritance you get a `Doctrine\DBAL\Schema\SchemaException: There is no column with name 'translatable_id' on table`. 
This is because a unique constraint is going to be set for the translation subclass but this class don't have this column. This comment describes it well and also suggest the fix: https://github.com/KnpLabs/DoctrineBehaviors/issues/307#issuecomment-231264716

Add doctrine join table inheritance compatibility

---

tests/Fixtures/Contract/Translatable/ExtendedTranslatableInterface.php
tests/Fixtures/Contract/Translatable/TranslatableEntityWithCustomInterface.php
tests/Fixtures/Contract/Translatable/TranslatableEntityWithCustomInterfaceTranslation.php
tests/ORM/Translatable/TranslatableTest.php
utils/phpstan-behaviors/src/Type/StaticTranslationTypeHelper.php

If I use my own TranslatableInterface instead of the one provided by the bundle, phpstan throw an error. 
Here an example 
```php
use Acme\Contract\TranslatableInterface;
class Product implements TranslatableInterface
{
}
```
```php
use Knp\DoctrineBehaviors\Contract\Entity\TranslatableInterface as KnpTranslatableInterface;
interface TranslatableInterface extends KnpTranslatableInterface
{
}
```
Thx !
PS: Sorry I've closed the previous PR (#695) after a mistake :sweat:

Fix phpstan behaviors to allow an interface inherited from TranslatableInterface
