- .travis.yml
- composer.json
> Yaml-Lint for travis.

- src/ORM/Sluggable/SluggableSubscriber.php
**Use case** : I need to create a slug from a field which is updated in a entity listener.
**Problem** : The ``generateSlug`` method is called before any other listener/subscriber, because it is registered as lifecycle events which are prioritary (no matter the "priority" attribute).
**Solution** : Call the ``generateSlug`` method from the ``SluggableSubscriber``.
> Call generateSlug from SluggableSubscriber

- src/Model/Tree/NodeInterface.php
this function was missing in the interface
> added missing function to interface

- config/orm-services.yml
- src/Model/Translatable/TranslatableMethods.php
- src/Model/Translatable/TranslatableProperties.php
- src/ORM/Translatable/DefaultLocaleCallable.php
- src/ORM/Translatable/TranslatableSubscriber.php
- tests/Knp/DoctrineBehaviors/ORM/TranslatableTest.php
> Add Callable function to override default language

- README.md
- src/Model/SoftDeletable/SoftDeletableMethods.php
- tests/Knp/DoctrineBehaviors/ORM/SoftDeletableTest.php
Closes #219.
Also should prevent such PRs as #215.
> Add documentation about restore() method in Softdeleteable 

- README.md
I think in examples better to use `example.com` domain
> Change mysite.com with example.com

- README.md
Reorder list of behaviors with ASC order in docs to make it easier to read and add few missing behaviors to the list
> Reorder list of behaviors with ASC order in docs

- README.md
Hi,
Just up to date documentation to match with current code.
ksom
> Update tree documentation

- composer.json
> composer: bump to PHPUnit ~4.8

- tests/Knp/DoctrineBehaviors/ORM/TimestampableTest.php
Here is a PR to fix the tests in `master` as suggested in #326 ;) Hope that helps.
> Fix Timestampable tests

- README.md
BTW, we have problems with `master` branch: some tests failed. It's a bit annoying to review PRs when tests always failed. We definitely should fix it for `master` branch.
> Use svg image for Travis badge and show status of master branch

- src/Model/Tree/Node.php
- src/Model/Tree/NodeInterface.php
Fixes https://github.com/KnpLabs/DoctrineBehaviors/issues/74
> Add nullable setchildof

- src/Model/Translatable/TranslatableMethods.php
Do not persist new translations if empty.
> [Translatable] Do not persist new translations if empty

- src/ORM/Tree/Tree.php
PR rebased from https://github.com/KnpLabs/DoctrineBehaviors/pull/75 by @raziel057
> [Tree] Add possibility to pass extra parameters in getTree

- .editorconfig
- .travis.yml
- README.md
- composer.json
> Travis: bump to min PHP 7.2, test stable doctrine/orm

- src/Model/Translatable/TranslatableMethods.php
Cherry pick of https://github.com/KnpLabs/DoctrineBehaviors/pull/82
> [Translatable] Fix property access on twig

- phpstan.neon
- src/Bundle/DependencyInjection/DoctrineBehaviorsExtension.php
- src/Model/Translatable/TranslatableMethodsTrait.php
- src/Provider/LocationProvider.php
> add default location provider

- composer.json
- src/Model/Translatable/TranslatableMethodsTrait.php
- src/Model/Translatable/TranslationMethodsTrait.php
- src/ORM/Translatable/TranslatableSubscriber.php
- tests/DatabaseLoader.php
- tests/Fixtures/ORM/Translatable/AbstractTranslatableEntity.php
- tests/Fixtures/ORM/Translatable/AbstractTranslatableEntityTranslation.php
- tests/Fixtures/ORM/Translatable/ExtendedTranslatableEntity.php
- tests/Fixtures/ORM/Translatable/ExtendedTranslatableEntityTranslation.php
- tests/ORM/TranslatableInheritanceTest.php
> [Translation] add abstract class support

- README.md
- composer.json
- docs/timestampable.md
- docs/tree.md
- docs/uuidable.md
- phpstan.neon
- src/Contract/Entity/UuidableInterface.php
- src/Contract/Model/Tree/NodeInterface.php
- src/Model/Sortable/SortableMethodsTrait.php
- src/Model/Sortable/SortablePropertiesTrait.php
- src/Model/Sortable/SortableTrait.php
- src/Model/Tree/NodeTrait.php
- src/Model/Uuidable/UuidableMethodsTrait.php
- src/Model/Uuidable/UuidablePropertiesTrait.php
- src/Model/Uuidable/UuidableTrait.php
- src/ORM/Filterable/FilterableRepositoryTrait.php
- src/ORM/Tree/TreeSubscriber.php
- src/ORM/Tree/TreeTrait.php
- src/ORM/Uuidable/UuidableSubscriber.php
- tests/DatabaseLoader.php
- tests/Fixtures/ORM/SluggableEntity.php
- tests/Fixtures/ORM/SluggableMultiEntity.php
- tests/Fixtures/ORM/TreeNodeEntity.php
- tests/Fixtures/ORM/UuidableEntity.php
- tests/ORM/FilterableRepositoryTest.php
- tests/ORM/Tree/NodeTest.php
- tests/ORM/UuidableTest.php
- upgrade/rector/doctrine-behaviors-20.yaml
> [Uuidable] init

- composer.json
> Add missing dependency symplify/package-builder

- composer.json
> composer: use the symfony/security for symfony 4.4

- phpstan.neon
- src/Model/Translatable/TranslatableMethodsTrait.php
- tests/ORM/TranslatableInheritanceTest.php
- tests/ORM/TranslatableTest.php
> add setTranslations()

- composer.json
- upgrade/rector/doctrine-behaviors-20.yaml
Covers https://github.com/KnpLabs/DoctrineBehaviors/pull/442/commits/4e0320964954c8d8ad079b9aafc2fbe2f4159cc6#diff-653a74d4646aeb3ba7c8383c1d0933f1
> [Rector] Add Upgrade set for id property on translations

- src/Repository/DefaultSluggableRepository.php
Closes https://github.com/KnpLabs/DoctrineBehaviors/issues/476
> Fix slug uniqueness check function

- docs/soft-deletable.md
- docs/timestampable.md
> Update trait names in docs

- src/Repository/DefaultSluggableRepository.php
This PR aims to fix the bug reported in issue #482
> Fix slug uniqueness

- src/Provider/LocaleProvider.php
https://github.com/KnpLabs/DoctrineBehaviors/issues/500
> Attempted to call an undefined method named "getDefaultLocale"

- .github/workflows/coding_standard.yaml
- .github/workflows/linter.yaml
- .github/workflows/phpstan.yaml
- .github/workflows/rector_ci.yaml
- .travis.yml
Github Actions fail for some legacy account reason :/
> Workflows can't be executed on this repository. Please check your payment method or billing status.
https://twitter.com/webKnjaZ/status/1194964915506831362
> Add Github Actions

- README.md
- composer.json
- config/services.yaml
- phpstan.neon
- src/DoctrineBehaviorsBundle.php
- tests/HttpKernel/DoctrineBehaviorsKernel.php
- tests/ORM/UuidableTest.php
Package changes for the correct operation of symfony-flex auto-generated recipe
> Sympony bandle name conventions

- docs/translatable.md
[Translation now needs Id](https://www.tomasvotruba.com/blog/2019/12/30/doctrine-behaviors-2-0-reloaded/)
closes #540
> Add translation id field information

- ecs.yaml
- src/Bundle/DoctrineBehaviorsBundle.php
- src/DoctrineBehaviorsBundle.php
> Fix broken old bandle register class

- src/Model/Tree/TreeNodeMethodsTrait.php
- tests/ORM/TreeNodeTest.php
> Bugfix for Tree: getRealMaterializedPath

- docs/blameable.md
Hello,
This PR will fix : 
- 1 typo in `docs/blameable.md`
Cheers! :robot:
> Fix typo in docs/blameable.md

- config/services.yaml
- docs/timestampable.md
- src/EventSubscriber/TimestampableSubscriber.php
- tests/ORM/TimestampableMakeEntityTest.php
To fix #553
Move datetime type field from database type detection to service configuration
> Avoid database access loading metadata

- src/Model/Uuidable/UuidablePropertiesTrait.php
uuid - should be protected, so it can be overwritten.
> UuidablePropertiesTrait - uuid should be protected

- docs/translatable.md
> Fix typo in translatable doc

- .gitattributes
- .github/workflows/code_checks.yaml
- .github/workflows/linter.yaml
added .gitattributes with export-ignore tests, docs...
> added .gitattributes with export-ignore tests, docs

- src/Model/Translatable/TranslatableMethodsTrait.php
- tests/ORM/TranslatableTest.php
Fixes #562 
Actually partially reverted d9dde97 and added the test.
> Fallback to default locale if country locale fallback returns empty result

- ecs.php
- src/Contract/Entity/TimestampableInterface.php
- src/Model/Timestampable/TimestampableMethodsTrait.php
To fix this issue : https://github.com/KnpLabs/DoctrineBehaviors/issues/558
> Allow getCreatedAt and getUpdatedAt to return null

- README.md
Closes https://github.com/KnpLabs/DoctrineBehaviors/issues/645
> README: update Rector config path

- composer.json
Close #652 
**EDIT:** Hum, this won't be easy as expected :P
> fix(deps): remove unnecessary PHP 8 polyfill, close #652

- src/Model/Sluggable/SluggableMethodsTrait.php
> fix generateSlugValue method signature

- composer.json
https://github.com/symfony/translation-contracts/releases/tag/v3.0.0
> bump symfony/translation-contracts

- phpstan.neon
- rector.php
- src/EventSubscriber/SluggableEventSubscriber.php
- src/EventSubscriber/TranslatableEventSubscriber.php
- src/Model/Tree/TreeNodeMethodsTrait.php
- tests/Fixtures/Entity/TranslatableCustomIdentifierEntity.php
- tests/ORM/Blameable/BlameableWithEntityTest.php
- tests/ORM/Translatable/TranslatableTest.php
- utils/phpstan-behaviors/src/Exception/PHPStanTypeException.php
- utils/phpstan-behaviors/src/Type/StaticTranslationTypeHelper.php
- utils/phpstan-behaviors/src/Type/TranslatableGetTranslationsDynamicMethodReturnTypeExtension.php
- utils/phpstan-behaviors/src/Type/TranslatableTranslateDynamicMethodReturnTypeExtension.php
- utils/phpstan-behaviors/src/Type/TranslationGetTranslatableDynamicMethodReturnTypeExtension.php
- utils/phpstan-behaviors/src/Type/TranslationTypeHelper.php
- for PHPStan upgrade, ref https://github.com/phpstan/phpstan-src/commit/db2f7fb9e7928de68665ca09a3e1002d8a329b33
Closes https://github.com/KnpLabs/DoctrineBehaviors/pull/643
> [rector] apply PHP 8 upgrade + upgrade phpstan utils to PHPStan 1.3

- composer.json
- ecs.php
- phpstan.neon
- rector.php
- src/Model/Tree/TreeNodeMethodsTrait.php
- tests/config/config_test.php
- utils/phpstan-behaviors/src/Type/TranslatableGetTranslationsDynamicMethodReturnTypeExtension.php
- bump to newer PHPStan
- bump to PHPStan 1.6.3
> Bump Rector and PHPStan dependencies, upgrade ECS and Rector to new configs
